/*
 * This file is automatically generated.
 * Run 'npm run generate:locales' to update.
 */
import type { CompanyDefinition } from '../../..';
import name_pattern from './name_pattern';
import suffix from './suffix';

const company: CompanyDefinition = {
  name_pattern,
  suffix,
};

export default company;
