/*
 * This file is automatically generated.
 * Run 'npm run generate:locales' to update.
 */
import type { LocationDefinition } from '../../..';
import state from './state';

const location: LocationDefinition = {
  state,
};

export default location;
