/*
 * This file is automatically generated.
 * Run 'npm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import metadata from './metadata';
import person from './person';

const yo_NG: LocaleDefinition = {
  metadata,
  person,
};

export default yo_NG;
