/*
 * This file is automatically generated.
 * Run 'npm run generate:locales' to update.
 */
import type { AnimalDefinition } from '../../..';
import cat from './cat';
import dog from './dog';
import horse from './horse';

const animal: AnimalDefinition = {
  cat,
  dog,
  horse,
};

export default animal;
