/*
 * This file is automatically generated.
 * Run 'npm run generate:locales' to update.
 */
import type { PhoneNumberDefinition } from '../../..';
import formats from './formats';

const phone_number: PhoneNumberDefinition = {
  formats,
};

export default phone_number;
