/*
 * This file is automatically generated.
 * Run 'npm run generate:locales' to update.
 */
import type { CommerceDefinition } from '../../..';
import product_name from './product_name';

const commerce: CommerceDefinition = {
  product_name,
};

export default commerce;
