/*
 * This file is automatically generated.
 * Run 'npm run generate:locales' to update.
 */
import type { HackerDefinition } from '../../..';
import abbreviation from './abbreviation';

const hacker: HackerDefinition = {
  abbreviation,
};

export default hacker;
