/*
 * This file is automatically generated.
 * Run 'npm run generate:locales' to update.
 */
import type { ColorDefinition } from '../../..';
import human from './human';

const color: ColorDefinition = {
  human,
};

export default color;
