/*
 * This file is automatically generated.
 * Run 'npm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import game from './game';
import internet from './internet';
import location from './location';
import metadata from './metadata';
import person from './person';
import phone_number from './phone_number';

const en_US: LocaleDefinition = {
  game,
  internet,
  location,
  metadata,
  person,
  phone_number,
};

export default en_US;
