/*
 * This file is automatically generated.
 * Run 'npm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import en from '../locales/en';
import en_NG from '../locales/en_NG';

export const faker = new Faker({
  locale: [en_NG, en, base],
});
