/*
 * This file is automatically generated.
 * Run 'npm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import en from '../locales/en';
import en_US from '../locales/en_US';

export const faker = new Faker({
  locale: [en_US, en, base],
});
