/*
 * This file is automatically generated.
 * Run 'npm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import en from '../locales/en';
import hr from '../locales/hr';

export const faker = new Faker({
  locale: [hr, en, base],
});
