/*
 * This file is automatically generated.
 * Run 'npm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import en from '../locales/en';
import hu from '../locales/hu';

export const faker = new Faker({
  locale: [hu, en, base],
});
