/*
 * This file is automatically generated.
 * Run 'npm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import en from '../locales/en';
import it from '../locales/it';

export const faker = new Faker({
  locale: [it, en, base],
});
