/*
 * This file is automatically generated.
 * Run 'npm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import en from '../locales/en';
import ne from '../locales/ne';

export const faker = new Faker({
  locale: [ne, en, base],
});
