/*
 * This file is automatically generated.
 * Run 'npm run generate:locales' to update.
 */
import type { ColorDefinition } from '../../..';
import space from './space';

const color: ColorDefinition = {
  space,
};

export default color;
