/*
 * This file is automatically generated.
 * Run 'npm run generate:locales' to update.
 */
import type { AnimalDefinition } from '../../..';
import bear from './bear';
import crocodilia from './crocodilia';
import lion from './lion';
import type_ from './type';

const animal: AnimalDefinition = {
  bear,
  crocodilia,
  lion,
  type: type_,
};

export default animal;
