/*
 * This file is automatically generated.
 * Run 'npm run generate:locales' to update.
 */
import type { ScienceDefinition } from '../../..';
import chemicalElement from './chemicalElement';
import unit from './unit';

const science: ScienceDefinition = {
  chemicalElement,
  unit,
};

export default science;
