/*
 * This file is automatically generated.
 * Run 'npm run generate:locales' to update.
 */
import type { WordDefinition } from '../../..';
import adjective from './adjective';

const word: WordDefinition = {
  adjective,
};

export default word;
