/*
 * This file is automatically generated.
 * Run 'npm run generate:locales' to update.
 */
import type { AnimalDefinition } from '../../..';
import horse from './horse';

const animal: AnimalDefinition = {
  horse,
};

export default animal;
