/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import company from './company';
import game_ from './game';
import genre from './genre';
import rating from './rating';

const game = {
  company,
  game: game_,
  genre,
  rating,
};

export default game;
