/*
 * This file is automatically generated.
 * Run 'npm run generate:locales' to update.
 */
import type { CommerceDefinition } from '../../..';
import department from './department';
import product_description from './product_description';
import product_name from './product_name';

const commerce: CommerceDefinition = {
  department,
  product_description,
  product_name,
};

export default commerce;
