/*
 * This file is automatically generated.
 * Run 'npm run generate:locales' to update.
 */
import type { CommerceDefinition } from '../../..';
import department from './department';

const commerce: CommerceDefinition = {
  department,
};

export default commerce;
