/*
 * This file is automatically generated.
 * Run 'npm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import game from './game';
import lorem from './lorem';
import metadata from './metadata';
import person from './person';

const en_BORK: LocaleDefinition = {
  game,
  lorem,
  metadata,
  person,
};

export default en_BORK;
