/*
 * This file is automatically generated.
 * Run 'npm run generate:locales' to update.
 */
import name_ from './name';
import prefix from './prefix';

const team = {
  name: name_,
  prefix,
};

export default team;
